export const stations = [
  {id:"lv",name:"Linke Herzkammer",short:"Linke Kammer",circuit:"body",oxygen:"reich",position:[.58,-.67,.5],label:[1.14,-1.13],text:"Hier beginnt der Körperkreislauf. Die linke Kammer pumpt das Blut mit Sauerstoff in die Aorta.",term:"Herzkammer",definition:"Ein Herzraum, der Blut aus dem Herzen herauspumpt.",next:"Durch die Aortenklappe in die Aorta."},
  {id:"aorta",name:"Aorta & Körperarterien",short:"Aorta",circuit:"body",oxygen:"reich",position:[2.27,-.9,.1],label:[2.02,-.12],text:"Die Aorta ist die Hauptschlagader. Über Arterien und kleine Arteriolen kommt das Blut zu den Organen.",term:"Arteriole",definition:"Eine kleine Arterie vor den Kapillaren.",next:"Vom Herzen weg zu den Körperkapillaren."},
  {id:"body",name:"Körperkapillaren",short:"Körperkapillaren",circuit:"body",oxygen:"wechsel-body",position:[0,-2.6,.1],label:[0,-3.17],text:"Die Zellen bekommen Sauerstoff und Nährstoffe. Das Blut nimmt Kohlendioxid und andere Abfallstoffe auf.",term:"Kapillaren",definition:"Winzige Gefäße, durch deren dünne Wände Stoffe ausgetauscht werden.",next:"Das jetzt sauerstoffarme Blut fließt in die Venolen."},
  {id:"veins",name:"Venen & Hohlvenen",short:"Hohlvenen",circuit:"body",oxygen:"arm",position:[-2.27,-.9,.1],label:[-2.04,-.12],text:"Die Venen sammeln das Blut aus dem Körper. Über die obere und untere Hohlvene fließt es zum Herzen zurück.",term:"Hohlvenen",definition:"Zwei große Venen. Sie bringen Blut aus dem Körper zum rechten Vorhof.",next:"In den rechten Vorhof."},
  {id:"ra",name:"Rechter Vorhof",short:"Rechter Vorhof",circuit:"body",oxygen:"arm",position:[-.58,.35,.5],label:[-1.18,.62],text:"Der rechte Vorhof nimmt das sauerstoffarme Blut aus dem Körper auf und gibt es an die rechte Kammer weiter.",term:"Vorhof",definition:"Ein Herzraum, der ankommendes Blut aufnimmt.",next:"Durch die Trikuspidalklappe in die rechte Kammer."},
  {id:"rv",name:"Rechte Herzkammer",short:"Rechte Kammer",circuit:"lung",oxygen:"arm",position:[-.58,-.67,.5],label:[-1.14,-1.13],text:"Hier beginnt der Lungenkreislauf. Die rechte Kammer pumpt das sauerstoffarme Blut zur Lunge.",term:"Lungenkreislauf",definition:"Der kleine Kreislauf zwischen Herz und Lunge.",next:"Durch die Pulmonalklappe in die Lungenarterien."},
  {id:"pa",name:"Lungenarterien",short:"Lungenarterien",circuit:"lung",oxygen:"arm",position:[-1.65,1.33,.35],label:[-1.67,1.35],text:"Sie führen Blut vom Herzen zur Lunge. Dieses Blut enthält wenig Sauerstoff.",term:"Arterie",definition:"Ein Gefäß, das Blut vom Herzen wegführt. Der Name sagt nichts über den Sauerstoffgehalt aus.",next:"Zu den Kapillaren in beiden Lungen."},
  {id:"lungs",name:"Lungenkapillaren",short:"Lungenkapillaren",circuit:"lung",oxygen:"wechsel-lung",position:[0,2.4,.1],label:[0,3.12],text:"Das Blut gibt Kohlendioxid ab, das wir ausatmen. Gleichzeitig nimmt es Sauerstoff aus der eingeatmeten Luft auf.",term:"Gasaustausch",definition:"Sauerstoff geht ins Blut; Kohlendioxid geht aus dem Blut in die Lunge.",next:"Das sauerstoffreiche Blut fließt in die Lungenvenen."},
  {id:"pv",name:"Lungenvenen",short:"Lungenvenen",circuit:"lung",oxygen:"reich",position:[1.1,1.35,.45],label:[1.62,1.35],text:"Die Lungenvenen bringen das Blut mit frischem Sauerstoff von der Lunge zurück zum Herzen.",term:"Vene",definition:"Ein Gefäß, das Blut zum Herzen führt. Lungenvenen enthalten sauerstoffreiches Blut.",next:"In den linken Vorhof."},
  {id:"la",name:"Linker Vorhof",short:"Linker Vorhof",circuit:"lung",oxygen:"reich",position:[.58,.35,.5],label:[1.18,.62],text:"Der linke Vorhof nimmt das Blut aus der Lunge auf. Von hier kommt es in die linke Kammer. Dann beginnt der Weg erneut.",term:"Mitralklappe",definition:"Das Ventil zwischen linkem Vorhof und linker Kammer.",next:"Durch die Mitralklappe zurück in die linke Kammer."}
];
export const valves = [
  {id:"tricuspid",name:"Trikuspidalklappe",label:[-1.45,-.36],position:[-.58,-.15,.55],text:"Sie liegt zwischen rechtem Vorhof und rechter Kammer. Sie verhindert, dass Blut in den Vorhof zurückfließt.",term:"Herzklappe",definition:"Ein Ventil, das Blut nur in eine Richtung durchlässt.",oxygen:"arm",circuit:"body"},
  {id:"pulmonary",name:"Pulmonalklappe",label:[-1.72,.94],position:[-1.06,.07,.58],text:"Sie liegt am Ausgang der rechten Kammer zur Lungenschlagader. Sie verhindert den Rückfluss in die rechte Kammer.",term:"Pulmonal",definition:"Betrifft die Lunge.",oxygen:"arm",circuit:"lung"},
  {id:"mitral",name:"Mitralklappe",label:[1.45,-.36],position:[.58,-.15,.55],text:"Sie liegt zwischen linkem Vorhof und linker Kammer. Sie verhindert, dass Blut in den Vorhof zurückfließt.",term:"Herzklappe",definition:"Ein Ventil, das Blut nur in eine Richtung durchlässt.",oxygen:"reich",circuit:"lung"},
  {id:"aortic",name:"Aortenklappe",label:[1.7,.94],position:[.4,.78,.65],text:"Sie liegt am Ausgang der linken Kammer zur Aorta. Sie verhindert den Rückfluss aus der Aorta in die linke Kammer.",term:"Aorta",definition:"Hauptschlagader; die größte Arterie im Körper.",oxygen:"reich",circuit:"body"}
];
export const quizzes = [
  {target:"lv",prompt:"Wo beginnt der Körperkreislauf?",choices:["Rechte Kammer","Linke Kammer","Rechter Vorhof","Linker Vorhof"],correct:1,why:"Die linke Kammer pumpt Blut über die Aorta in den Körper."},
  {target:"lungs",prompt:"Wo nimmt das Blut frischen Sauerstoff auf?",choices:["Körperkapillaren","Hohlvenen","Lungenkapillaren","Aorta"],correct:2,why:"In den Lungenkapillaren nimmt das Blut Sauerstoff auf und gibt Kohlendioxid ab."},
  {target:"ra",prompt:"Wohin bringen die Hohlvenen das Blut?",choices:["Linker Vorhof","Rechter Vorhof","Linke Kammer","Lunge"],correct:1,why:"Die beiden Hohlvenen münden in den rechten Vorhof."},
  {target:"pa",prompt:"Welche Gefäße führen sauerstoffarmes Blut zur Lunge?",choices:["Lungenvenen","Körperarterien","Hohlvenen","Lungenarterien"],correct:3,why:"Lungenarterien führen vom Herzen weg, obwohl das Blut sauerstoffarm ist."},
  {target:"body",prompt:"Wo bekommen die Körperzellen Sauerstoff und Nährstoffe?",choices:["Körperkapillaren","Lungenvenen","Rechter Vorhof","Aorta"],correct:0,why:"Der Stoffaustausch mit den Körperzellen findet in den Kapillaren statt."},
  {target:"pv",prompt:"Was bringen die Lungenvenen zum Herzen?",choices:["Sauerstoffarmes Blut","Sauerstoffreiches Blut","Luft","Nur Kohlendioxid"],correct:1,why:"Nach dem Gasaustausch in der Lunge enthält das Blut viel Sauerstoff."},
  {target:"rv",prompt:"Welche Kammer pumpt das Blut zur Lunge?",choices:["Linke Kammer","Linker Vorhof","Rechte Kammer","Rechter Vorhof"],correct:2,why:"Die rechte Herzkammer ist die Pumpe des Lungenkreislaufs."},
  {target:"aorta",prompt:"Wie heißt die Hauptschlagader?",choices:["Hohlvene","Lungenvene","Venole","Aorta"],correct:3,why:"Die Aorta ist die größte Arterie und beginnt an der linken Kammer."},
  {target:"la",prompt:"In welchem Herzraum kommt das Blut aus der Lunge an?",choices:["Linker Vorhof","Rechter Vorhof","Rechte Kammer","Aorta"],correct:0,why:"Die Lungenvenen bringen das Blut in den linken Vorhof."},
  {target:"veins",prompt:"Was gilt für alle Venen?",choices:["Sie enthalten immer wenig Sauerstoff","Sie führen vom Herzen weg","Sie führen zum Herzen hin","Sie sind alle Kapillaren"],correct:2,why:"Die Flussrichtung zum Herzen ist entscheidend. Der Sauerstoffgehalt kann unterschiedlich sein."}
];
export const sequences = {
  body:{name:"Körperkreislauf",items:["Linke Kammer","Aorta / Arterien","Körperkapillaren","Venen / Hohlvenen","Rechter Vorhof"],ids:["lv","aorta","body","veins","ra"]},
  lung:{name:"Lungenkreislauf",items:["Rechte Kammer","Lungenarterien","Lungenkapillaren","Lungenvenen","Linker Vorhof"],ids:["rv","pa","lungs","pv","la"]}
};
export const oral = {
  body:{name:"Körperkreislauf",text:"Die linke Herzkammer pumpt sauerstoffreiches Blut über die Aorta und die Arterien in den Körper. In den Kapillaren gibt es Sauerstoff und Nährstoffe an die Zellen ab und nimmt Kohlendioxid und andere Abfallstoffe auf. Das sauerstoffarme Blut fließt über die Venen und die beiden Hohlvenen in den rechten Vorhof zurück.",checks:["Linke Kammer und Aorta genannt","Stoffaustausch in den Kapillaren erklärt","Rückweg zum rechten Vorhof genannt"]},
  lung:{name:"Lungenkreislauf",text:"Die rechte Herzkammer pumpt sauerstoffarmes Blut über die Lungenarterien zur Lunge. Dort gibt das Blut Kohlendioxid ab und nimmt Sauerstoff auf. Über die Lungenvenen kommt es sauerstoffreich in den linken Vorhof zurück.",checks:["Rechte Kammer und Lungenarterien genannt","Gasaustausch in der Lunge erklärt","Lungenvenen und linken Vorhof genannt"]}
};
