const nerveCirculationGlossary = {
  "Hinterhauptloch": "Öffnung unten im Schädel. Hier geht das Gehirn ins Rückenmark über.",
  "Wirbelkanal": "Geschützter Raum in der Wirbelsäule, in dem das Rückenmark liegt.",
  "Lendenwirbel": "Wirbel im unteren Rücken.",
  "Segment": "Ein Abschnitt; hier ein Abschnitt des Rückenmarks.",
  "Spinalnerven": "Rückenmarksnerven. Sie verbinden das Rückenmark mit dem Körper.",
  "Hirnnerven": "Nerven, die direkt mit dem Gehirn verbunden sind.",
  "Nervenzellkörper": "Hauptteile der Nervenzellen mit dem Zellkern.",
  "motorisch": "Steuert Bewegungen der Muskeln.",
  "sensibel": "Leitet Empfindungen weiter, z. B. Berührung oder Schmerz.",
  "Neuron": "Anderes Wort für Nervenzelle.",
  "Nervus": "Lateinisches Wort für Nerv; abgekürzt N.",
  "Trigeminus": "Drillingsnerv. Er teilt sich in drei große Äste.",
  "N. ophthalmicus": "Augenhöhlennerv; erster Ast des Drillingsnervs.",
  "N. maxillaris": "Oberkiefernerv; zweiter Ast des Drillingsnervs.",
  "N. mandibularis": "Unterkiefernerv; dritter Ast des Drillingsnervs.",
  "Facialis": "Gesichtsnerv; steuert unter anderem die Gesichtsmuskeln.",
  "mimische Muskulatur": "Muskeln für den Gesichtsausdruck, z. B. beim Lächeln.",
  "vegetativ": "Arbeitet weitgehend automatisch, ohne dass du bewusst daran denkst.",
  "Stoffwechsel": "Der Körper verarbeitet Stoffe, um Energie und Baustoffe zu gewinnen.",
  "Sympathikus": "Macht den Körper bereit für Anstrengung und Stress.",
  "Parasympathikus": "Unterstützt Ruhe, Erholung und Verdauung.",
  "Pupille": "Öffnung in der Mitte des Auges. Durch sie fällt Licht ins Auge.",
  "Bronchien": "Atemwege, durch die Luft in der Lunge weiterströmt.",
  "Hirnbasis": "Unterseite des Gehirns.",
  "irreparabel": "Nicht mehr rückgängig zu machen.",
  "kardiovaskulär": "Betrifft Herz und Blutgefäße.",
  "Arterie": "Blutgefäß, das Blut vom Herzen wegführt.",
  "Vene": "Blutgefäß, das Blut zum Herzen zurückführt.",
  "Kapillaren": "Winzige Blutgefäße. Hier tauschen Blut und Gewebe Stoffe aus.",
  "Aorta": "Hauptschlagader; die größte Arterie des Körpers.",
  "Arteriolen": "Kleine Arterien vor den Kapillaren.",
  "Venolen": "Kleine Venen nach den Kapillaren.",
  "Herzkammer": "Herzraum, der Blut aus dem Herzen herauspumpt.",
  "Vorhof": "Herzraum, der ankommendes Blut aufnimmt.",
  "Tunica interna": "Innere Schicht der Gefäßwand; direkt am Blut.",
  "Tunica media": "Mittlere Schicht der Gefäßwand; enthält Muskeln.",
  "Tunica externa": "Äußere Schicht der Gefäßwand; gibt Halt.",
  "Aorta ascendens": "Aufsteigender Teil der Hauptschlagader.",
  "Aortenklappe": "Ventil zwischen linker Herzkammer und Hauptschlagader.",
  "Hohlvenen": "Zwei große Venen, die Blut aus dem Körper zum Herzen bringen.",
  "Stoffwechselendprodukte": "Abfallstoffe, die bei der Arbeit der Zellen entstehen.",
  "Taschenklappen": "Kleine Ventile. Sie verhindern, dass Blut zurückfließt.",
  "Muskelpumpe": "Bewegte Muskeln drücken auf Venen und helfen dem Blut zum Herzen.",
  "Perforansvenen": "Verbindungsvenen zwischen oberflächlichen und tiefen Venen.",
  "mikroskopisch": "So klein, dass man ein Mikroskop zum Erkennen braucht.",
  "weitmaschig": "Mit größeren Abständen zwischen den Gefäßen.",
  "Kohlendioxid": "Abfallgas der Zellen. Es wird über die Lunge ausgeatmet.",
  "sauerstoffreich": "Enthält viel Sauerstoff.",
  "sauerstoffarm": "Enthält wenig Sauerstoff."
};

// Each entry refers to the printed script number in the marked September PDF.
const nerveCirculationRows = [
  [164, "Rückenmark", "Wo beginnt und endet das Rückenmark?", ["Es beginnt am Hinterhauptloch und geht aus dem verlängerten Mark hervor.", "Es ist etwa 1 cm dick und verläuft im Wirbelkanal bis etwa zum ersten oder zweiten Lendenwirbel."], ["Hinterhauptloch", "Wirbelkanal", "Lendenwirbel"]],
  [165, "Rückenmark", "Welche fünf Abschnittsgruppen hat das Rückenmark?", ["Hals-, Brust-, Lenden-, Kreuzbein- und Steißbeinabschnitte."], ["Segment"], false, "Auf der Folie werden fünf Gruppen angekündigt, aber nur vier aufgezählt. Die Kreuzbeinabschnitte fehlen in der Liste."],
  [166, "Rückenmark", "Wie sind graue und weiße Substanz im Rückenmark angeordnet?", ["Innen: graue Substanz mit Nervenzellkörpern.", "Außen: weiße Substanz mit Nervenfasern, die Signale nach oben und unten leiten."], ["Nervenzellkörper"]],
  [166, "Rückenmark", "Was gehört zum Vorderhorn und was zum Hinterhorn?", ["Vorderhorn: motorische Nervenzellen für die Muskelbewegung.", "Hinterhorn: Hier kommen sensible Signale an, z. B. Berührung und Schmerz."], ["motorisch", "sensibel", "Neuron"]],
  [170, "Hirnnerven", "Welche Nerven gehören zum peripheren Nervensystem?", ["31 Paare Spinalnerven und 12 Paare Hirnnerven."], ["Spinalnerven", "Hirnnerven"], false, "Die Folie nennt 31–32 Spinalnerven und 12 Hirnnerven. Die übliche anatomische Angabe ist 31 beziehungsweise 12 Paare."],
  [171, "Hirnnerven", "Welche Bereiche versorgen die Hirnnerven?", ["Kopf und Hals sowie einen großen Teil der inneren Organe.", "Sie verbinden außerdem die Sinnesorgane mit dem Gehirn."], ["Hirnnerven"]],
  [172, "Hirnnerven", "Welche zwei Hirnnerven sind im Bild für Gefühl im Gesicht und für Mimik wichtig?", ["V: N. trigeminus (Drillingsnerv) für Empfindungen im Gesicht; er steuert auch Kaumuskeln.", "VII: N. facialis (Gesichtsnerv) für die mimische Muskulatur."], ["Trigeminus", "Facialis", "mimische Muskulatur"], true],
  [174, "Hirnnerven", "Welche Hirnnerven sind für den zahnärztlichen Bereich besonders wichtig?", ["Der fünfte Hirnnerv: N. trigeminus (Drillingsnerv).", "Der siebte Hirnnerv: N. facialis (Gesichtsnerv)."], ["Nervus"]],
  [174, "Hirnnerven", "Welche drei Äste hat der Drillingsnerv?", ["Augenhöhlennerv: N. ophthalmicus.", "Oberkiefernerv: N. maxillaris.", "Unterkiefernerv: N. mandibularis."], ["Trigeminus"]],
  [174, "Hirnnerven", "Welche Äste des Drillingsnervs versorgen die Zähne?", ["Oberkiefernerv (N. maxillaris): Zähne im Oberkiefer.", "Unterkiefernerv (N. mandibularis): Zähne und Zahnfleisch im Unterkiefer sowie die Unterlippe."], ["sensibel"]],
  [177, "Hirnnerven", "Wie heißt der siebte Hirnnerv und welche markierte Aufgabe hat er?", ["N. facialis, auch Gesichtsnerv.", "Er steuert die mimische Muskulatur, also die Muskeln für unseren Gesichtsausdruck."], ["mimische Muskulatur"]],
  [180, "Vegetatives Nervensystem", "Was regelt das vegetative Nervensystem?", ["Lebenswichtige Organfunktionen wie Atmung, Kreislauf und Stoffwechsel.", "Das läuft weitgehend automatisch ab."], ["vegetativ", "Stoffwechsel"]],
  [180, "Vegetatives Nervensystem", "Welche zwei Systeme unterscheidet man im vegetativen Nervensystem?", ["Sympathikus und Parasympathikus."], ["Sympathikus", "Parasympathikus"]],
  [181, "Vegetatives Nervensystem", "Wann sind Sympathikus und Parasympathikus besonders aktiv?", ["Sympathikus: bei körperlicher Arbeit und Stress.", "Parasympathikus: bei Ruhe, Essen, Verdauung und Ausscheidung."], ["Sympathikus", "Parasympathikus"]],
  [182, "Vegetatives Nervensystem", "Vergleiche im Bild: Was machen Sympathikus und Parasympathikus?", ["Sympathikus: Pupillen und Bronchien werden weiter, das Herz schlägt schneller. Die Verdauung wird gebremst.", "Parasympathikus: Pupillen und Bronchien werden enger, das Herz schlägt langsamer. Die Verdauung wird gefördert."], ["Pupille", "Bronchien"], true],
  [182, "Vegetatives Nervensystem", "Was zeigt das Bild bei Gallenblase und Harnblase?", ["Sympathikus: Gallenblase und Harnblase füllen sich; die Blasenentleerung wird gehemmt.", "Parasympathikus: Die Entleerung von Gallenblase und Harnblase wird gefördert."], ["Sympathikus", "Parasympathikus"], true],
  [183, "Vegetatives Nervensystem", "Welches Nervensystem passt zu Stress und welches zu Entspannung im Bild?", ["Stress und Anspannung: Sympathikus.", "Entspannung, Essen, Verdauung und Ausscheidung: Parasympathikus."], [], true],
  [185, "Gehirnversorgung", "Warum braucht das Gehirn ständig Sauerstoff?", ["Es hat einen sehr hohen Sauerstoffbedarf.", "Schon wenige Minuten ohne Sauerstoff können bleibende Schäden verursachen."], ["irreparabel"]],
  [185, "Gehirnversorgung", "Wie bekommt das Gehirn Sauerstoff und Nährstoffe?", ["Über ein System von Arterien an der Hirnbasis."], ["Arterie", "Hirnbasis"]],
  [187, "Kreisläufe", "Was ist das Herz-Kreislauf-System und wie heißt es noch?", ["Herz und Blutgefäße zusammen.", "Man nennt es auch kardiovaskuläres System."], ["kardiovaskulär"]],
  [187, "Kreisläufe", "Welche zwei Blutkreisläufe gibt es?", ["Lungenkreislauf: der kleine Kreislauf.", "Körperkreislauf: der große Kreislauf."], []],
  [189, "Blutgefäße", "Welche drei Arten von Blutgefäßen gibt es?", ["Arterien, Venen und Kapillaren."], ["Arterie", "Vene", "Kapillaren"]],
  [190, "Arterien", "Wohin führen Arterien das Blut und wie verläuft der Weg im Körper?", ["Arterien führen Blut vom Herzen weg.", "Im Körperkreislauf: linke Herzkammer → Aorta → Arterien → Arteriolen.", "Hier ist das Blut sauerstoffreich."], ["Herzkammer", "Aorta", "Arteriolen", "sauerstoffreich"]],
  [191, "Arterien", "Welche drei Wandschichten haben Arterien?", ["Tunica interna: innere Schicht, direkt am Blut.", "Tunica media: mittlere Schicht mit glatten Muskelzellen.", "Tunica externa: äußere Schicht aus Bindegewebe und elastischen Fasern."], ["Tunica interna", "Tunica media", "Tunica externa"]],
  [192, "Blutgefäße", "Wo findet im Gefäßbild der Stoffaustausch statt?", ["In den Kapillaren.", "Sauerstoff und Nährstoffe gehen zu den Zellen. Abfallstoffe gehen ins Blut."], ["Kapillaren", "Stoffwechselendprodukte"], true],
  [193, "Arterien", "Zeige im Bild die Hauptschlagader. Wie heißt sie?", ["Sie heißt Aorta und ist die größte Arterie des Körpers."], ["Aorta"], true],
  [194, "Arterien", "Zeige im Herzbild Aorta, Aorta ascendens und Aortenklappe.", ["Aorta: Hauptschlagader.", "Aorta ascendens: aufsteigender Teil der Hauptschlagader.", "Aortenklappe: zwischen linker Herzkammer und Aorta."], ["Aorta ascendens", "Aortenklappe"], true],
  [195, "Venen", "Wie kommt das Blut aus dem Körper zurück zum Herzen?", ["Aus den Kapillaren über Venolen und Venen.", "Dann über die obere und untere Hohlvene in den rechten Vorhof.", "Das Blut ist jetzt sauerstoffarm."], ["Venolen", "Hohlvenen", "Vorhof", "sauerstoffarm"]],
  [195, "Venen", "Was wird in den Kapillaren zwischen Blut und Körperzellen ausgetauscht?", ["Die Zellen bekommen Sauerstoff und Nährstoffe.", "Sie geben Kohlendioxid und andere Abfallstoffe an das Blut ab."], ["Kohlendioxid", "Stoffwechselendprodukte"]],
  [196, "Venen", "Was ist am Wandaufbau der Venen besonders?", ["Die äußere Schicht ist stärker ausgeprägt, die Muskelschicht schwächer als bei Arterien.", "Die innere Schicht bildet in vielen kleinen und mittelgroßen Venen Taschenklappen."], ["Taschenklappen"]],
  [196, "Venen", "Wie helfen Muskelpumpe und Venenklappen dem Blut?", ["Wenn Muskeln sich anspannen, drücken sie die Venen zusammen und schieben das Blut zum Herzen.", "Die Klappen verhindern, dass es zurückfließt."], ["Muskelpumpe", "Taschenklappen"]],
  [197, "Venen", "Was ist im Bild der Unterschied zwischen gesunder und kranker Vene?", ["Gesunde Vene: Die Klappen schließen und verhindern den Rückfluss.", "Kranke Vene im Bild: Die Klappen schließen nicht richtig. Blut fließt zurück."], ["Taschenklappen"], true],
  [198, "Venen", "Welche drei Arten von Beinvenen gibt es?", ["Tiefe Venen.", "Oberflächliche Venen.", "Perforansvenen: Sie verbinden beide miteinander."], ["Perforansvenen"]],
  [201, "Kapillaren", "Was sind Kapillaren und welche Gefäße verbinden sie?", ["Winzige, meist nur unter dem Mikroskop erkennbare Blutgefäße.", "Sie verbinden Arteriolen mit Venolen."], ["mikroskopisch", "Arteriolen", "Venolen"], false, "Auf der Folie steht zusätzlich das Wort „Arterien“ hinter „Venolen“. Gemeint ist die Verbindung von Arteriolen zu Venolen."],
  [202, "Kapillaren", "Wie hängt das Kapillarnetz vom Sauerstoffbedarf ab?", ["Hoher Sauerstoffbedarf: dichtes Kapillarnetz.", "Geringer Sauerstoffbedarf: weitmaschigeres Kapillarnetz."], ["weitmaschig"]],
  [206, "Kreisläufe", "Erkläre den Körper-Blutkreislauf kurz, als würdest du mündlich antworten.", ["Die linke Herzkammer pumpt sauerstoffreiches Blut über die Aorta und die Arterien in den Körper.", "In den Kapillaren gibt es Sauerstoff und Nährstoffe an die Zellen ab und nimmt Kohlendioxid und andere Abfallstoffe auf.", "Das sauerstoffarme Blut fließt über die Venen und die beiden Hohlvenen in den rechten Vorhof zurück."], ["Aorta", "Kapillaren", "Hohlvenen", "Vorhof"], true],
  [206, "Kreisläufe", "Zeige im Bild den Lungenkreislauf und erkläre den Weg des Blutes.", ["Aus der rechten Herzkammer fließt sauerstoffarmes Blut über die Lungenarterien zur Lunge.", "Dort gibt es Kohlendioxid ab und nimmt Sauerstoff auf.", "Über die Lungenvenen kommt es sauerstoffreich in den linken Vorhof zurück."], ["sauerstoffarm", "Kohlendioxid", "Vorhof"], true]
];

const nerveCirculationCards = nerveCirculationRows.map(([page, topic, question, answer, terms, imageAnswer = false, sourceNote], index) => ({
  id: `nc164-206-${String(index + 1).padStart(3, "0")}`,
  deck: "circulation",
  number: index + 1,
  scriptPage: page,
  topic,
  question,
  answer,
  terms,
  imageAnswer,
  slideImage: `assets/slides/marked-20260912/page-${page}.jpg`,
  ...(sourceNote ? { sourceNote } : {})
}));
